config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  get 'order_rerender_cart', to: 'orders#cart_rerender', as: :order_rerender_cart
  resources :line_items, only: [:create, :destroy, :update, :index]
  resources :products, only: [:show]
  resources :categories, only: [:index, :show]

  get 'products_search',to: 'products#search', as: :products_search
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'categories#index'
end

app/models/additional_description.rb
class AdditionalDescription < ActiveRecord::Base
  belongs_to :product
  validates :description, presence: true
  validates :title, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/carousel_item.rb
class CarouselItem < ActiveRecord::Base
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :image, :attachment_presence => true
	validates :title, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
			if current_item
				current_item.quantity += 1
			else
				current_item = line_items.build(product_id: product_id)
			end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	def total_quantity
		line_items.to_a.sum { |item| item.quantity }
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :image, :attachment_presence => true
	validates :title, :body, :presence => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than: 100 }
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	validates :name, :address, :city, :phone, presence: true
	validates :delivery_price, :product_price, :status, numericality: true, allow_blank: true
	after_create :set_product_price
	def add_item_from_cart(cart)
		cart.line_items.each do |line_item|
			line_item.cart_id = nil
			line_items << line_item
		end
		cart.destroy
	end
	def set_product_price
    self.product_price = line_items.to_a.sum {|item| item.total_price}
	end

	def total_price
		product_price + delivery_price
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
  include PgSearch
  validates :title, :description, :color, :price, presence: true
  validates :price, numericality: true
  pg_search_scope :search_by_title, against: :title,
                  using: {tsearch: {prefix: true}}
  paginates_per 3
  belongs_to :category
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images, :allow_destroy => true

  has_many :additional_descriptions, dependent: :destroy
  accepts_nested_attributes_for :additional_descriptions, :allow_destroy => true

  has_many :line_items
  before_destroy :line_item_ref

  private
    def line_item_ref
      if line_items.empty?
        return true
      else
        errors.add(:base, 'error')
        return false
      end
    end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :Product
  has_attached_file :image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360X390>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  def new
    if @cart.total_quantity == 0
      redirect_to root_path
    else
      @order = Order.new
    end
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        @order.add_item_from_cart(@cart)
        format.html { redirect_to root_path, notice: 'Спасибо за покупку, мы вам позвоним!' }
      else
        format.html { render :new }
      end
    end
  end

  def cart_rerender
    if @cart.total_quantity == 0
      render :js => "window.location = '#{root_path}'"
    else
      respond_to :js
    end
  end

  private

    def order_params
      params.require(:order).permit(:name, :city, :address, :phone)
    end
end

app/controllers/products_controller.rb
# Product controller
class ProductsController < InheritedResources::Base
  before_action :set_categories, only: :search
  before_action :set_keyword, only: :search
  def search
    if @keyword.blank? || (@keyword.length < 3)
      @products = Product.all.page(params[:page])
    else
      @products = Product.search_by_title(@keyword).page(params[:page])
    end
  end

  private

  def set_keyword
    @keyword = params[:search]
  end

  def set_categories
    @categories = Category.all
  end

  def product_params
    params.require(:product)
      .permit(:title, :color, :description, :category_id, :price)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def custom_currency(price)
		number_to_currency(price, unit: "", separator: ",", delimiter: " ")
	end
	def prefix_title
		'HandMade, Хэнд Мэйд в Челябинскe.'
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart_window.html.slim
.modal#cart-modal tabindex='-1' role='dialog' labelledby='modal-label' aria-hidden='true'
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close data-dismiss='modal' aria-label="Close"
          span aria-hidden='true' &times;
        h4.modal-title#modal-label Ваша корзина
        .modal-body
          p Вы только что добавили товар в Корзину, что будем делать дальше?
        .modal-footer
          button.btn.btn-default data-dismiss="modal" Продолжить покупки
          = link_to 'Оформить заказ', new_order_path , class: 'btn btn-primary'

app/views/layouts/_footer.html.slim
.section.submit-section
  .container
    .row
      .text-center
        h4 Подписка
        form.form-inline
          .form-group
            label.sr-only for='subs-email'
            input.form-control#subs-email type='email' placeholder='Enter email'
            button.btn.btn-default type='submit' Submit

footer.footer.text-center
  .container
    ul.list-inline
      li
        =link_to root_path
          =image_tag('facebook.png')
      li
        =link_to root_path
          =image_tag('twitter.png')
      li
        =link_to root_path
          =image_tag('google.png')
      li
        =link_to root_path
          =image_tag('vimeo.png')
    p
      |  Алисе наскучило  сидеть  с  сестрой  без  дела  на  берегу  реки;
    p
      |  разок-другой она заглянула в книжку, которую читала сестра, но там  не  было
      |  ни картинок, ни разговоров.
    p
      |       - Что толку в книжке, - подумала Алиса, - если в ней нет  ни  картинок,
      |  ни разговоров?
    ul.list-inline
      li
        a О нас
      li
        | -
      li
        a Как оформить заказ
      li
        | -
      li
        a Помощь
      li
        | -
      li
        a Доставка

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand'
        span.glyphicon.glyphicon-home
    .collapse.navbar-collapse

      = link_to  line_items_path,  'remote': true,
                                    'class': 'btn btn-default navbar-btn navbar-right pull-right cart-qty',
                                    'role': 'button',
                                    'data-toggle': 'modal',
                                    'data-target': '#cart-modal'
        span.glyphicon.glyphicon-shopping-cart
        .badge#product-qty = @cart.total_quantity
      = form_tag products_search_path, method: :get, class: ['navbar-form', 'navbar-right']
        .form-group
          =search_field_tag :search, params[:search], placeholder: 'Поиск по товарам', class: 'form-control'
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
  a
    span.glyphicon.glyphicon-phone
    i +7-909-082-7023
li
  =link_to 'О нас', page_path('about')
li
  a href='#' Как оформить заказ
li
  =link_to 'Помощь', page_path('help')
li
  a href='#' Доставка

app/views/layouts/application.html.slim
doctype html
html
  head
    =favicon_link_tag
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Hm Shop'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Hm Shop'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      .container
        == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield
      == render 'layouts/cart_window'
      == render 'layouts/footer'

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/help.html.slim
h1 Help